/* eslint-disable */
// Auto-generated mock data from user CSV
export const MOCK_DATA = [
  {
    "id": "mock-loc-0",
    "fullName": "340 E North Water",
    "clientId": "LOC-1000",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 2253.15,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:45.496Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.61886,
    "latitude": 41.88973,
    "zipCode": "60611",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-1",
    "fullName": "850 N Lake Shore Dr",
    "clientId": "LOC-1001",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1132.36,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:45.764Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.618512,
    "latitude": 41.89824,
    "zipCode": "60611",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-2",
    "fullName": "NEMA 14th Floor",
    "clientId": "LOC-1002",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1748.05,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:46.090Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: gym. Type: High Rise Apartment",
    "longitude": -87.797329,
    "latitude": 41.720901,
    "zipCode": "60453",
    "city": "Oak Lawn",
    "state": "IL"
  },
  {
    "id": "mock-loc-3",
    "fullName": "NEMA 16th Floor",
    "clientId": "LOC-1003",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 3887.45,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:46.424Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.797329,
    "latitude": 41.720901,
    "zipCode": "60453",
    "city": "Oak Lawn",
    "state": "IL"
  },
  {
    "id": "mock-loc-4",
    "fullName": "218 E Grand Ave",
    "clientId": "LOC-1004",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1809.4,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:46.692Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.622176,
    "latitude": 41.891896,
    "zipCode": "60611",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-5",
    "fullName": "633 W North Ave",
    "clientId": "LOC-1005",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 2872.12,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:46.970Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.644838,
    "latitude": 41.910594,
    "zipCode": "60610",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-6",
    "fullName": "Westlyn Apartments Warrenville",
    "clientId": "LOC-1006",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1131.24,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:47.200Z",
    "location1PropertyType": "Mid Rise Apartment",
    "location1MachineType": "Mixed",
    "notes": "Placement: amenity lounge. Type: Mid Rise Apartment",
    "longitude": -88.173023,
    "latitude": 41.817838,
    "state": "IL"
  },
  {
    "id": "mock-loc-7",
    "fullName": "1407 S Michigan Ave",
    "clientId": "LOC-1007",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1663.8,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:47.494Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.623652,
    "latitude": 41.863745,
    "zipCode": "60605",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-8",
    "fullName": "215 W Lake St",
    "clientId": "LOC-1008",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 3161.7,
    "totalNumberOfMachines": 3,
    "dateAdded": "2026-02-01T00:32:47.760Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: lobby. Type: High Rise Apartment",
    "longitude": -87.634651,
    "latitude": 41.885446,
    "zipCode": "60606",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-9",
    "fullName": "220 E Illinois St",
    "clientId": "LOC-1009",
    "status": "Active",
    "membershipLevel": "Platinum",
    "totalMonthlyRevenue": 4552.91,
    "totalNumberOfMachines": 4,
    "dateAdded": "2026-02-01T00:32:48.041Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Mixed",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.621541,
    "latitude": 41.891281,
    "zipCode": "60611",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-10",
    "fullName": "1001 S State",
    "clientId": "LOC-1010",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1866.1,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:48.348Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.627083,
    "latitude": 41.869956,
    "zipCode": "60605",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-11",
    "fullName": "1125 W Van Buren (Avra)",
    "clientId": "LOC-1011",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1622.18,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:48.686Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: lobby. Type: High Rise Apartment",
    "longitude": -87.655552,
    "latitude": 41.876383,
    "zipCode": "60607",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-12",
    "fullName": "369 W Grand (Onni)",
    "clientId": "LOC-1012",
    "status": "Active",
    "membershipLevel": "Platinum",
    "totalMonthlyRevenue": 5853.71,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:49.048Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.637643,
    "latitude": 41.891317,
    "zipCode": "60654",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-13",
    "fullName": "Wolf Point West",
    "clientId": "LOC-1013",
    "status": "Active",
    "membershipLevel": "Platinum",
    "totalMonthlyRevenue": 4658.81,
    "totalNumberOfMachines": 3,
    "dateAdded": "2026-02-01T00:32:49.348Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.632362,
    "latitude": 41.881953,
    "state": "IL"
  },
  {
    "id": "mock-loc-14",
    "fullName": "Hearthstone Apartments",
    "clientId": "LOC-1014",
    "status": "Active",
    "membershipLevel": "Bronze",
    "totalMonthlyRevenue": 400,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:49.519Z",
    "location1PropertyType": "Garden Style Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: clubhouse. Type: Garden Style Apartment",
    "longitude": -75.810108,
    "latitude": 41.565281,
    "zipCode": "18419",
    "city": "Factoryville",
    "state": "PA"
  },
  {
    "id": "mock-loc-15",
    "fullName": "Terrace Station",
    "clientId": "LOC-1015",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 3200,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:49.726Z",
    "location1PropertyType": "Mid Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: package room. Type: Mid Rise Apartment",
    "longitude": -79.273624,
    "latitude": 44.036653,
    "zipCode": "L4A 2Y3",
    "city": "Stouffville",
    "state": "CA-ON"
  },
  {
    "id": "mock-loc-16",
    "fullName": "Mukilteo elementary School Staff Room",
    "clientId": "LOC-1016",
    "status": "Active",
    "membershipLevel": "Bronze",
    "totalMonthlyRevenue": 180,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:49.927Z",
    "location1PropertyType": "School",
    "location1MachineType": "Traditional Combo",
    "notes": "Placement: breakroom. Type: School",
    "longitude": 7.611182,
    "latitude": 11.041876,
    "zipCode": "81",
    "city": "Zaria",
    "state": "NG-KD"
  },
  {
    "id": "mock-loc-17",
    "fullName": "Olympic View Middle",
    "clientId": "LOC-1017",
    "status": "Active",
    "membershipLevel": "Bronze",
    "totalMonthlyRevenue": 260,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:50.122Z",
    "location1PropertyType": "School",
    "location1MachineType": "Traditional Combo",
    "notes": "Placement: breakroom. Type: School",
    "longitude": -70.893939,
    "latitude": 41.903182,
    "zipCode": "02346",
    "city": "Middleboro",
    "state": "MA"
  },
  {
    "id": "mock-loc-18",
    "fullName": "Voyager Middle School",
    "clientId": "LOC-1018",
    "status": "Active",
    "membershipLevel": "Bronze",
    "totalMonthlyRevenue": 200,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:50.315Z",
    "location1PropertyType": "School",
    "location1MachineType": "Traditional Combo",
    "notes": "Placement: breakroom. Type: School",
    "longitude": -105.338776,
    "latitude": 45.101747,
    "zipCode": "59314",
    "city": "Biddle",
    "state": "MT"
  },
  {
    "id": "mock-loc-19",
    "fullName": "sage west loop",
    "clientId": "LOC-1019",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1500,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:50.537Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: lobby. Type: High Rise Apartment",
    "longitude": -87.641106,
    "latitude": 41.878033,
    "zipCode": "60661",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-20",
    "fullName": "river west lofts",
    "clientId": "LOC-1020",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 2200,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:50.871Z",
    "location1PropertyType": "Mid Rise Apartment",
    "location1MachineType": "Cantaloupe Smart Store",
    "notes": "Placement: amenity lounge. Type: Mid Rise Apartment",
    "longitude": -87.64892,
    "latitude": 41.896379,
    "zipCode": "60642",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-21",
    "fullName": "avenir",
    "clientId": "LOC-1021",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1100,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:51.147Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: lobby. Type: High Rise Apartment",
    "longitude": -87.615228,
    "latitude": 41.674461,
    "zipCode": "60628",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-22",
    "fullName": "Aston",
    "clientId": "LOC-1022",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 2600,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:51.403Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: package room. Type: High Rise Apartment",
    "longitude": -87.632362,
    "latitude": 41.881953,
    "state": "IL"
  },
  {
    "id": "mock-loc-23",
    "fullName": "77 W Huron",
    "clientId": "LOC-1023",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 3000,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:51.682Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: laundry room. Type: High Rise Apartment",
    "longitude": -87.630766,
    "latitude": 41.894665,
    "zipCode": "60654",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-24",
    "fullName": "Forward Pickleball",
    "clientId": "LOC-1024",
    "status": "Active",
    "membershipLevel": "Bronze",
    "totalMonthlyRevenue": 200,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:51.854Z",
    "location1PropertyType": "Gym",
    "location1MachineType": "Micromart",
    "notes": "Placement: lobby. Type: Gym",
    "longitude": -78.86475,
    "latitude": 40.13153,
    "city": "Hooversville",
    "state": "PA"
  },
  {
    "id": "mock-loc-25",
    "fullName": "Jenkins Restoration",
    "clientId": "LOC-1025",
    "status": "Active",
    "membershipLevel": "Bronze",
    "totalMonthlyRevenue": 450,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:52.032Z",
    "location1PropertyType": "Other",
    "location1MachineType": "HaHa",
    "notes": "Placement: amenity lounge. Type: Other",
    "longitude": -65.884788,
    "latitude": -47.748376,
    "zipCode": "9050",
    "city": "Puerto Deseado",
    "state": "AR-Z"
  },
  {
    "id": "mock-loc-26",
    "fullName": "Larkspur",
    "clientId": "LOC-1026",
    "status": "Active",
    "membershipLevel": "Bronze",
    "totalMonthlyRevenue": 400,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:52.197Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: mail room. Type: High Rise Apartment",
    "longitude": -122.535461,
    "latitude": 37.935145,
    "state": "CA"
  },
  {
    "id": "mock-loc-27",
    "fullName": "The Parlor",
    "clientId": "LOC-1027",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1200,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:52.369Z",
    "location1PropertyType": "Mid Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: mail room. Type: Mid Rise Apartment",
    "longitude": -8.073458,
    "latitude": 51.913059,
    "zipCode": "P25 K2T6",
    "city": "Castlemartyr",
    "state": "IE-CO"
  },
  {
    "id": "mock-loc-28",
    "fullName": "Rocket Lab",
    "clientId": "LOC-1028",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 2000,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:52.566Z",
    "location1PropertyType": "Manufacturing",
    "location1MachineType": "Other",
    "notes": "Placement: breakroom. Type: Manufacturing",
    "longitude": 145.318533,
    "latitude": -38.085933,
    "zipCode": "3977",
    "city": "Melbourne",
    "state": "AU-VIC"
  },
  {
    "id": "mock-loc-29",
    "fullName": "Fitzgerald Cadillac",
    "clientId": "LOC-1029",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1800,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:52.747Z",
    "location1PropertyType": "Other",
    "location1MachineType": "Cantaloupe Smart Store",
    "notes": "Placement: other. Type: Other",
    "longitude": -106.592918,
    "latitude": 52.140198,
    "zipCode": "S7N 2A7",
    "city": "Saskatoon",
    "state": "CA-SK"
  },
  {
    "id": "mock-loc-30",
    "fullName": "Bayside Chrysler Dodge Ram Jeep",
    "clientId": "LOC-1030",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 2000,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:52.922Z",
    "location1PropertyType": "Other",
    "location1MachineType": "Cantaloupe Smart Store",
    "notes": "Placement: other. Type: Other",
    "longitude": -87.906068,
    "latitude": 43.185615,
    "state": "WI"
  },
  {
    "id": "mock-loc-31",
    "fullName": "Winfield Elementary",
    "clientId": "LOC-1031",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 2300,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:53.096Z",
    "location1PropertyType": "School",
    "location1MachineType": "Stockwell",
    "notes": "Placement: breakroom. Type: School",
    "longitude": -96.997208,
    "latitude": 37.240318,
    "state": "KS"
  },
  {
    "id": "mock-loc-32",
    "fullName": "Bayside Toyota Prince Frederick",
    "clientId": "LOC-1032",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1300,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:53.309Z",
    "location1PropertyType": "Other",
    "location1MachineType": "Pico Cooler",
    "notes": "Placement: other. Type: Other",
    "longitude": -78.25239,
    "latitude": 39.193764,
    "zipCode": "22602",
    "city": "Winchester",
    "state": "VA"
  },
  {
    "id": "mock-loc-33",
    "fullName": "Bayside Kia of Waldorf",
    "clientId": "LOC-1033",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 2600,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:53.505Z",
    "location1PropertyType": "Other",
    "location1MachineType": "Cantaloupe Smart Store",
    "notes": "Placement: other. Type: Other",
    "longitude": 1.076699,
    "latitude": 51.064801,
    "zipCode": "CT21 6HQ",
    "city": "Hythe",
    "state": "GB-ENG"
  },
  {
    "id": "mock-loc-34",
    "fullName": "Mansfield Service Partners",
    "clientId": "LOC-1034",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 2000,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:53.693Z",
    "location1PropertyType": "Office",
    "location1MachineType": "HaHa",
    "notes": "Placement: breakroom. Type: Office",
    "longitude": 0.122914,
    "latitude": 51.808782,
    "zipCode": "CM21 0JT",
    "city": "Sawbridgeworth",
    "state": "GB-ENG"
  },
  {
    "id": "mock-loc-35",
    "fullName": "Kippford at Kemah Crossing",
    "clientId": "LOC-1035",
    "status": "Active",
    "membershipLevel": "Bronze",
    "totalMonthlyRevenue": 500,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:53.878Z",
    "location1PropertyType": "Garden Style Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: mail room. Type: Garden Style Apartment",
    "longitude": 15.932134,
    "latitude": 46.800293,
    "city": "Tieschen",
    "state": "AT-6"
  },
  {
    "id": "mock-loc-36",
    "fullName": "San Palmilla",
    "clientId": "LOC-1036",
    "status": "Active",
    "membershipLevel": "Bronze",
    "totalMonthlyRevenue": 500,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:54.041Z",
    "location1PropertyType": "Mid Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: amenity lounge. Type: Mid Rise Apartment",
    "longitude": -2.115235,
    "latitude": 14.357812,
    "state": "ML-5"
  },
  {
    "id": "mock-loc-37",
    "fullName": "Ondina Bellevue",
    "clientId": "LOC-1037",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1500,
    "totalNumberOfMachines": 3,
    "dateAdded": "2026-02-01T00:32:54.215Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: gym. Type: High Rise Apartment",
    "longitude": -62.742735,
    "latitude": 46.091447,
    "city": "Belfast",
    "state": "CA-PE"
  },
  {
    "id": "mock-loc-38",
    "fullName": "Copal Bellevue",
    "clientId": "LOC-1038",
    "status": "Active",
    "membershipLevel": "Bronze",
    "totalMonthlyRevenue": 1000,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:54.393Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "HaHa",
    "notes": "Placement: gym. Type: High Rise Apartment",
    "longitude": -87.930532,
    "latitude": 44.470875,
    "zipCode": "54311",
    "city": "Green Bay",
    "state": "WI"
  },
  {
    "id": "mock-loc-39",
    "fullName": "Metropolitan Appliances",
    "clientId": "LOC-1039",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1500,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:54.603Z",
    "location1PropertyType": "Warehouse",
    "location1MachineType": "HaHa",
    "notes": "Placement: breakroom. Type: Warehouse",
    "longitude": -81.102486,
    "latitude": 32.05412,
    "zipCode": "31401",
    "city": "Savannah",
    "state": "GA"
  },
  {
    "id": "mock-loc-40",
    "fullName": "Wolf Point East",
    "clientId": "LOC-1040",
    "status": "Active",
    "membershipLevel": "Platinum",
    "totalMonthlyRevenue": 5449,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:54.826Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.632362,
    "latitude": 41.881953,
    "state": "IL"
  },
  {
    "id": "mock-loc-41",
    "fullName": "2335 N Lincoln Ave",
    "clientId": "LOC-1041",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1075,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:55.101Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: gym. Type: High Rise Apartment",
    "longitude": -87.647162,
    "latitude": 41.925008,
    "zipCode": "60614",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-42",
    "fullName": "2345 N Lincoln Ave",
    "clientId": "LOC-1042",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1332,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:55.375Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: gym. Type: High Rise Apartment",
    "longitude": -87.647182,
    "latitude": 41.92504,
    "zipCode": "60614",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-43",
    "fullName": "50 Canterfield",
    "clientId": "LOC-1043",
    "status": "Active",
    "membershipLevel": "Bronze",
    "totalMonthlyRevenue": 200,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:55.554Z",
    "location1PropertyType": "Garden Style Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: clubhouse. Type: Garden Style Apartment",
    "longitude": -88.290836,
    "latitude": 42.076355,
    "zipCode": "60118",
    "city": "West Dundee",
    "state": "IL"
  },
  {
    "id": "mock-loc-44",
    "fullName": "2200 Progress",
    "clientId": "LOC-1044",
    "status": "Active",
    "membershipLevel": "Bronze",
    "totalMonthlyRevenue": 805,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:55.768Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: other. Type: High Rise Apartment",
    "longitude": -85.74534,
    "latitude": 38.34126,
    "zipCode": "47130",
    "city": "Jeffersonville",
    "state": "IN"
  },
  {
    "id": "mock-loc-45",
    "fullName": "520 N Kingsbury",
    "clientId": "LOC-1045",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 3314,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:56.040Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.640153,
    "latitude": 41.891032,
    "zipCode": "60654",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-46",
    "fullName": "1140 S Wabash",
    "clientId": "LOC-1046",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 2333,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:56.298Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.626304,
    "latitude": 41.868085,
    "zipCode": "60605",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-47",
    "fullName": "808 S Michigan",
    "clientId": "LOC-1047",
    "status": "Active",
    "membershipLevel": "Platinum",
    "totalMonthlyRevenue": 6000,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:56.570Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: lobby. Type: High Rise Apartment",
    "longitude": -87.62455,
    "latitude": 41.87168,
    "zipCode": "60605",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-48",
    "fullName": "360 W Hubbard",
    "clientId": "LOC-1048",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1950,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:56.821Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.638456,
    "latitude": 41.890281,
    "zipCode": "60654",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-49",
    "fullName": "111 W Wacker",
    "clientId": "LOC-1049",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 3550,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:57.079Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.631387,
    "latitude": 41.88656,
    "zipCode": "60601",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-50",
    "fullName": "1114  W Carroll",
    "clientId": "LOC-1050",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1961,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:57.325Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.655422,
    "latitude": 41.888011,
    "zipCode": "60607",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-51",
    "fullName": "750 N Dearborn",
    "clientId": "LOC-1051",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 2368,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:57.568Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: laundry room. Type: High Rise Apartment",
    "longitude": -87.630109,
    "latitude": 41.896294,
    "zipCode": "60654",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-52",
    "fullName": "1130 N Dearborn",
    "clientId": "LOC-1052",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1027,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:57.843Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: laundry room. Type: High Rise Apartment",
    "longitude": -87.630346,
    "latitude": 41.902894,
    "zipCode": "60610",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-53",
    "fullName": "29 S LaSalle",
    "clientId": "LOC-1053",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1534,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:58.099Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.631813,
    "latitude": 41.881169,
    "zipCode": "60603",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-54",
    "fullName": "Argentum",
    "clientId": "LOC-1054",
    "status": "Active",
    "membershipLevel": "Bronze",
    "totalMonthlyRevenue": 850,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:58.259Z",
    "location1PropertyType": "Warehouse",
    "location1MachineType": "Micromarket",
    "notes": "Placement: breakroom. Type: Warehouse",
    "longitude": 148.953442,
    "latitude": -32.9999,
    "zipCode": "2866",
    "city": "Boomey",
    "state": "AU-NSW"
  },
  {
    "id": "mock-loc-55",
    "fullName": "617 W Bittersweet",
    "clientId": "LOC-1055",
    "status": "Active",
    "membershipLevel": "Platinum",
    "totalMonthlyRevenue": 6250,
    "totalNumberOfMachines": 4,
    "dateAdded": "2026-02-01T00:32:58.534Z",
    "location1PropertyType": "Shelter",
    "location1MachineType": "Traditional Combo",
    "notes": "Placement: lobby. Type: Shelter",
    "longitude": -87.645605,
    "latitude": 41.95576,
    "zipCode": "60613",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-56",
    "fullName": "469 W Huron",
    "clientId": "LOC-1056",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 2670,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:32:58.778Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: mail room. Type: High Rise Apartment",
    "longitude": -87.641207,
    "latitude": 41.894304,
    "zipCode": "60654",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-57",
    "fullName": "640 N Wells",
    "clientId": "LOC-1057",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1253,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:59.017Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.634451,
    "latitude": 41.893681,
    "zipCode": "60654",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-58",
    "fullName": "450 Warrenville Rd",
    "clientId": "LOC-1058",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 2100,
    "totalNumberOfMachines": 3,
    "dateAdded": "2026-02-01T00:32:59.202Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: clubhouse. Type: High Rise Apartment",
    "longitude": -88.06064,
    "latitude": 41.809328,
    "zipCode": "60532",
    "city": "Lisle",
    "state": "IL"
  },
  {
    "id": "mock-loc-59",
    "fullName": "1000 S Clark",
    "clientId": "LOC-1059",
    "status": "Active",
    "membershipLevel": "Platinum",
    "totalMonthlyRevenue": 4700,
    "totalNumberOfMachines": 3,
    "dateAdded": "2026-02-01T00:32:59.436Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.631221,
    "latitude": 41.869486,
    "zipCode": "60605",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-60",
    "fullName": "222 W Erie",
    "clientId": "LOC-1060",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1150,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:59.711Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: package room. Type: High Rise Apartment",
    "longitude": -87.635406,
    "latitude": 41.894251,
    "zipCode": "60654",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-61",
    "fullName": "545 N McClurg",
    "clientId": "LOC-1061",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 2100,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:32:59.962Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: mail room. Type: High Rise Apartment",
    "longitude": -87.617387,
    "latitude": 41.892274,
    "zipCode": "60611",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-62",
    "fullName": "1333 S Wabash",
    "clientId": "LOC-1062",
    "status": "Active",
    "membershipLevel": "Bronze",
    "totalMonthlyRevenue": 1000,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:33:00.304Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.625329,
    "latitude": 41.864712,
    "zipCode": "60605",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-63",
    "fullName": "1730 N Clark",
    "clientId": "LOC-1063",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 2705,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:33:00.554Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.633699,
    "latitude": 41.913848,
    "zipCode": "60614",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-64",
    "fullName": "166 N Aberdeen",
    "clientId": "LOC-1064",
    "status": "Active",
    "membershipLevel": "Silver",
    "totalMonthlyRevenue": 1005,
    "totalNumberOfMachines": 1,
    "dateAdded": "2026-02-01T00:33:00.804Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Stockwell",
    "notes": "Placement: amenity lounge. Type: High Rise Apartment",
    "longitude": -87.654805,
    "latitude": 41.885002,
    "zipCode": "60609",
    "city": "Chicago",
    "state": "IL"
  },
  {
    "id": "mock-loc-65",
    "fullName": "1401 S State",
    "clientId": "LOC-1065",
    "status": "Active",
    "membershipLevel": "Gold",
    "totalMonthlyRevenue": 2425,
    "totalNumberOfMachines": 2,
    "dateAdded": "2026-02-01T00:33:01.120Z",
    "location1PropertyType": "High Rise Apartment",
    "location1MachineType": "Micromart",
    "notes": "Placement: lobby. Type: High Rise Apartment",
    "longitude": -87.626939,
    "latitude": 41.863741,
    "zipCode": "60605",
    "city": "Chicago",
    "state": "IL"
  }
];
